#!/usr/bin/env python
import gtk
import appindicator
import os
import commands
import gtk
import sys

class AMDIndicator:
    def __init__(self):
	self.ind = appindicator.Indicator("AMD Indicator",
                                           "indicator-messages",
                                           appindicator.CATEGORY_APPLICATION_STATUS)
	self.ind.set_status(appindicator.STATUS_ACTIVE)
	self.ind.set_attention_icon("indicator-messages-new")
	self.ind.set_icon_theme_path("/usr/lib/amdindicator/")
	self.isIntegrated = self.checkIntegrated()
	self.ind.set_icon('intel')
	if not self.isIntegrated:
	    self.ind.set_icon('amd')
	self.setAdditionals()
        self.menu_setup()
        self.ind.set_menu(self.menu)

    def menu_setup(self):
        self.menu = gtk.Menu()
	self.info_item = gtk.MenuItem(self.rendererString())
	self.info_item.set_sensitive(False)
	self.info_item.show()
	self.seperator_item = gtk.SeparatorMenuItem()
	self.seperator_item.show()
	self.switch_item = gtk.MenuItem("Quick switch graphics processor")
	self.switch_item.connect("activate", self.switch)
	self.switch_item.show()
	self.seperator2_item = gtk.SeparatorMenuItem()
	self.seperator2_item.show()
	self.ccc_item = gtk.MenuItem("Catalyst Control Center")
        self.ccc_item.connect("activate", self.openccc)
        self.ccc_item.show()
	self.cccsu_item = gtk.MenuItem("Catalyst Control Center (Admin)")
        self.cccsu_item.connect("activate", self.opencccsu)
        self.cccsu_item.show()
	self.menu.append(self.info_item)
	self.menu.append(self.seperator_item)
	self.menu.append(self.switch_item)
	self.menu.append(self.seperator2_item)
	self.menu.append(self.ccc_item)
	self.menu.append(self.cccsu_item)

    def setAdditionals(self):
	if self.isIntegrated:
	    os.system("gconftool-2 --type Boolean --set /apps/compiz-1/plugins/opengl/screen0/options/sync_to_vblank True")
	else:
	    os.system("gconftool-2 --type Boolean --set /apps/compiz-1/plugins/opengl/screen0/options/sync_to_vblank False")

    def switch(self, dude):
	self.showRebootDialog()
	if self.isIntegrated:
	    self.switchToDiscrete()
	else:
	    self.switchToIntegrated()
	

    def openccc(self, dude):
	os.system("/usr/bin/amdcccle")

    def opencccsu(self, dude):
	os.system("/usr/bin/amdxdg-su -c /usr/bin/amdcccle")

    def showRebootDialog(self):
	message = "The X server will restart now.\nSave all your work-in-progress\nbefore pressing OK button."
	dialog = gtk.MessageDialog(None, gtk.DIALOG_MODAL, gtk.MESSAGE_INFO,
                                       gtk.BUTTONS_NONE, message)
	dialog.set_deletable(False)
	dialog.connect('delete_event', self.ignore)
	dialog.add_button(gtk.STOCK_OK, gtk.RESPONSE_OK)
	response = dialog.run()
	dialog.destroy()

    def ignore(*args):
	return gtk.TRUE

    def checkIntegrated(self):
	stat, out = commands.getstatusoutput("amdconfig --pxl")
	if "Discrete" in out:
	    return False
	else:
	    return True

    def rendererString(self):
	stat, out = commands.getstatusoutput('glxinfo | grep "OpenGL renderer string"')
	out = out.replace("OpenGL renderer string", "Using")
	return out

    def switchToIntegrated(self):
	os.system("sudo /usr/lib/amdindicator/igpuon")

    def switchToDiscrete(self):
	os.system("sudo /usr/lib/amdindicator/dgpuon")

    def main(self):
        gtk.main()

if __name__ == "__main__":
    indicator = AMDIndicator()
    indicator.main()
