#!/bin/bash
# Get sudo password
sudo_password="$( gksudo --print-pass --message 'Provide permission to make system changes:\nType your password or press Cancel.' -- : 2>/dev/null )"
# Check for null entry or cancellation.
if [[ ${?} != 0 || -z ${sudo_password} ]]
then
    exit 4
fi
# Check that the password is valid.
if ! sudo -kSp '' [ 1 ] <<<"${sudo_password}" 2>/dev/null
then
    exit 4
fi
# Execute sudo action
sudo -Sp '' ln -sf /usr/lib/amdindicator/amd-light.png /usr/lib/amdindicator/amd.png <<<"${sudo_password}"
killall python /usr/bin/amd-indicator
/usr/bin/amd-indicator
